### ISSUE TITLE
The specified core (0) does not exist.

### ISSUE THREAD

**Issue by lorenzomonta** [hacker1024/coretemp#2]
I don't understand how I can run coretemp?
Can you help me?

tnks

**Comment by lorenzomonta** [comment]
@hacker1024 can you help me? plz

**Comment by hacker1024** [comment]
Just run `coretemp`. Is there a problem?

**Comment by lorenzomonta** [comment]
When i run coretemp, this is the output "The specified core (0) does not exist."
But if i run brew list I can see coretemp correctlly installed

**Comment by hacker1024** [comment]
This is fixed in master, and will be included in the next release.
#1.

**Comment by chandlerc** [comment]
Any luck pushing a release with this?

**Comment by hacker1024** [comment]
Sorry for the delay. I'll try to get it done today.

**Comment by chandlerc** [comment]
No stress and thanks! (I've got a locally built version, but this makes it simpler to suggest to others.)
